apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv  # Name of your PV
  #namespace: dev  # Namespace where you want to create the PV (usually PVs are cluster-wide, but you can specify it here for organization)
spec:
  capacity:
    storage: 1Gi  # Specify the capacity you need
  accessModes:
    - ReadWriteOnce  # Access mode (RWO, ROX, RWX)
  persistentVolumeReclaimPolicy: Retain  # Policy for reclaiming the volume
  storageClassName: gp2  # Must match the storage class in your PVC
  hostPath:  # Example for hostPath (use for testing, not recommended for production)
    path: /data/db  # Path on the host (only for testing)
